name: Neat Starter
title: FaVU 30 let
intro: >-
  Rok FaVU je celoroční festival akcí uspořádaných 

  u příležitosti 30. výročí od založení Fakulty výtvarných umění VUT v Brně. Na této stránce najdete přehled událostí nebo projeků, které k výročí vznikly.


  <iframe width="560" height="315" src="https://www.youtube.com/embed/xNN7iTA57jM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


  V rámci propagační strategie k výročí vzniku fakulty vznikla taky série memes, v nichž vystupují pedagogové a pedagožky FaVU. Z této stránky si obrázky můžete volně stáhnout a dál šířit. Používejte je ale prosím tak, aby nové memes nikomu neubližovaly.
author: FaVU 30 let
url: favu.vut.cz
